import xml.dom.minidom

class XmlFormatter:
    """XML格式化工具"""
    
    @staticmethod
    def format_xml(text: str, indent: int = 4) -> str:
        """
        格式化XML字符串
        """
        if not text:
            return ""
        try:
            # removing whitespace between tags first to avoid double spacing
            text = "".join(line.strip() for line in text.splitlines())
            
            # Using minidom
            dom = xml.dom.minidom.parseString(text)
            # toprettyxml adds a lot of whitespace, we try to mitigate
            formatted = dom.toprettyxml(indent=" " * indent)
            
            # Remove empty lines generated by toprettyxml if dealing with mixed content
            # But simple approach:
            return "\n".join([line for line in formatted.splitlines() if line.strip()])
        except Exception as e:
            return f"[错误] XML格式化失败: {str(e)}"
